# Configuration for the Datadog Agent
hostname: "clonehero_datadog"

# Tags to categorize metrics, logs, and traces
tags:
  - "backend"
  - "datadog"
  - "microservices"
  - "monitoring"
  - "logs"
  - "apm"
  - "tracing"
  - "prometheus"

# Datadog API key for authentication
api_key: ${DD_API_KEY}

# Enable log collection
logs_enabled: true

# APM tracer configuration
apm_config:
  enabled: true

# Log collection configuration
logs_config:
  enabled: true
