groups:
  - name: system_alerts
    rules:
      - alert: HighCPUUsage
        expr: node_cpu_seconds_total{mode="idle"} < 20
        for: 2m
        labels:
          severity: warning
        annotations:
          summary: "High CPU Usage detected"
          description: "CPU usage is over 80% for more than 2 minutes."

      - alert: HighMemoryUsage
        expr: node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes * 100 < 15
        for: 2m
        labels:
          severity: warning
        annotations:
          summary: "High Memory Usage detected"
          description: "Memory usage is over 85% for more than 2 minutes."

      - alert: ServiceDown
        expr: up == 0
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "Service {{ $labels.instance }} is down"
          description: "The service {{ $labels.instance }} has been unreachable for 1 minute."

      - alert: DatabaseDown
        expr: pg_up == 0
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "Postgres Database Down"
          description: "The Postgres database has been unreachable for 1 minute."

      - alert: RedisDown
        expr: redis_up == 0
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "Redis Server Down"
          description: "The Redis service is not responding."
