global:
  scrape_interval: 15s
  evaluation_interval: 15s

alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - "clonehero_alertmanager:9093"

rule_files:
  - "/etc/prometheus/alert.rules.yml"

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "redis"
    static_configs:
      - targets: ["clonehero_redis:6379"]

  - job_name: "postgres"
    static_configs:
      - targets: ["clonehero_postgres:5432"]

  - job_name: "node_exporter"
    static_configs:
      - targets: ["clonehero_node_exporter:9100"]

  - job_name: "nginx_exporter"
    static_configs:
      - targets: ["clonehero_nginx_exporter:9113"]