global:
  resolve_timeout: 5m

route:
  receiver: "email"
  group_by: ["alertname", "service"]

receivers:
  - name: "email"
    email_configs:
      - to: "your-email@example.com"
        from: "alertmanager@example.com"
        smarthost: "smtp.gmail.com:587"
        auth_username: "your-email@example.com"
        auth_password: "${EMAIL_PASSWORD}"
        require_tls: true

  - name: "slack"
    slack_configs:
      - channel: "#alerts"
        api_url: "https://hooks.slack.com/services/YOUR/SLACK/WEBHOOK"
        text: "{{ range .Alerts }}{{ .Annotations.summary }}\n{{ .Annotations.description }}\n{{ end }}"